name: HoneyChest
main: HoneyChest\HoneyChest
version: 0.0.0
api: [1.7.1]
load: POSTWORLD
author: rain318
description: HoneyChest Plugin
website: https://github.com/rain318/HoneyChest
commands:
 test:
  description: "This is a test command"
  usage: "/test <example> [player]"
  permission: myplugin.example